name: f1_rating_system
version: 1.0.0
profile: f1_rating_system

model-paths: ["models"]

models:
  f1_rating_system:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: intermediate
