data:
  constructors_csv: 'data/raw/constructors.csv'
  drivers_csv: 'data/raw/drivers.csv'
  results_csv: 'data/raw/results.csv'
  status_csv: 'data/raw/status.csv'
  races_csv: 'data/raw/races.csv'
  preprocessed_path: 'data/interim/preprocessed_data.csv'
  features_path: 'data/interim/features.csv'
  modelled_path: 'data/interim/modelled_data.csv'
  goat_path: 'data/processed/goat.csv'
  hist_path: 'data/processed/hist.csv'
  2024_path: 'data/processed/2024.csv'
  one_off_path: 'data/processed/one_off.json'
  metrics_path: 'models/metrics.json'
  params_path: 'models/params.yaml'
  colour_path: 'data/processed/con_colours.csv'
  
model:
  opt_params:
    pbounds:
      'c': [10, 1000]
      'k': [10, 1000]
      'w': [0, 2]
    'n_iter': 20
    'init_points': 20
    'random_state': 1
  start_score: 1500