data:
  colour_csv: 'data/raw/constructor_colours.csv'
  constructors_csv: 'data/raw/constructors.csv'
  constructor_year_csv: 'data/raw/constructor_year.csv'
  drivers_csv: 'data/raw/drivers.csv'
  results_csv: 'data/raw/results.csv'
  status_csv: 'data/raw/status.csv'
  races_csv: 'data/raw/races.csv'
  preprocessed_path: 'data/interim/preprocessed_data.csv'
  features_path: 'data/interim/features.csv'
  modelled_path: 'data/interim/modelled_data.csv'
  metrics_path: 'models/metrics.json'
  params_path: 'models/params.yaml'
  hist_path: 'data/processed/hist.csv'
  last_race_path: 'data/processed/last_race.json'
  avg_goat_path: 'data/processed/avg_goat.csv'
  avg_hist_path: 'data/processed/avg_hist.csv'
  cur_dri_path: 'data/processed/cur_dri.csv'
  dri_imp_path: 'data/processed/dri_imp.csv'
  cur_con_path: 'data/processed/cur_con.csv'
  con_imp_path: 'data/processed/con_imp.csv'

model:
  opt_params:
    pbounds:
      'c': [10, 1000]
      'k': [10, 1000]
      'w': [0, 2]
    'n_iter': 20
    'init_points': 20
    'random_state': 1
  start_score: 1500