-- noqa: disable=CP02

SELECT
    statusId AS status_id,
    LOWER(status) AS driver_status,
    CASE
        WHEN
            LOWER(status) = 'finished' OR LOWER(status) LIKE '%lap%'
            THEN 'finished'
        WHEN LOWER(status) IN (
            'collision',
            'collision damage',
            'accident',
            'spun off',
            '107% rule',
            'did not qualify',
            'stalled',
            'did not prequalify',
            'damage'
        ) THEN 'driver retirement'
        WHEN LOWER(status) IN (
            'engine',
            'transmission',
            'clutch',
            'electrical',
            'hydraulics',
            'gearbox',
            'radiator',
            'suspension',
            'brakes',
            'overheating',
            'mechanical',
            'tyre',
            'driver seat',
            'puncture',
            'driveshaft',
            'retired',
            'fuel pressure',
            'front wing',
            'water pressure',
            'refuelling',
            'wheel',
            'throttle',
            'steering',
            'technical',
            'electronics',
            'broken wing',
            'heat shield fire',
            'exhaust',
            'oil leak',
            'wheel rim',
            'water leak',
            'fuel pump',
            'track rod',
            'oil pressure',
            'pneumatics',
            'engine fire',
            'tyre puncture',
            'out of fuel',
            'wheel nut',
            'handling',
            'rear wing',
            'fire',
            'fuel system',
            'oil line',
            'fuel rig',
            'launch control',
            'fuel',
            'power loss',
            'safety',
            'drivetrain',
            'ignition',
            'chassis',
            'battery',
            'halfshaft',
            'crankshaft',
            'safety concerns',
            'not restarted',
            'alternator',
            'differential',
            'wheel bearing',
            'physical',
            'vibrations',
            'underweight',
            'safety belt',
            'oil pump',
            'fuel leak',
            'injection',
            'distributor',
            'turbo',
            'cv joint',
            'water pump',
            'spark plugs',
            'fuel pipe',
            'oil pipe',
            'axle',
            'water pipe',
            'magneto',
            'supercharger',
            'engine misfire',
            'ers',
            'power unit',
            'brake duct',
            'seat',
            'debris',
            'cooling system',
            'undertray',
            'disqualified'
        ) THEN 'constructor retirement'
        WHEN LOWER(status) IN (
            'driver unwell',
            'eye injury',
            'fatal accident',
            'illness',
            'injured',
            'injury',
            'not classified',
            'withdrew',
            'excluded'
        ) THEN 'misc retirement'
        ELSE LOWER(status)
    END AS driver_status_group

FROM {{ source('source', 'status') }}
