c: !!python/object/apply:numpy._core.multiarray.scalar
- &id001 !!python/object/apply:numpy.dtype
  args:
  - f8
  - false
  - true
  state: !!python/tuple
  - 3
  - <
  - null
  - null
  - null
  - -1
  - -1
  - 0
- !!binary |
  RcWyGOaHeEA=
k: !!python/object/apply:numpy._core.multiarray.scalar
- *id001
- !!binary |
  Vsr1gk0lW0A=
w: !!python/object/apply:numpy._core.multiarray.scalar
- *id001
- !!binary |
  BerC1YWL+z8=
